/**
 * Bilingual word pools used to compose product names. A product name is
 * `<base> <variant> <size>`, and the Thai name is the parallel composition of the same
 * three records — so English and Thai never drift apart.
 * คลังคำสองภาษาสำหรับประกอบชื่อสินค้า ชื่อไทยประกอบจากระเบียนชุดเดียวกับชื่ออังกฤษ
 *
 * Pool sizes are a hard requirement, not a style preference: 8 bases x 8 variants x
 * 8 sizes = 512 combinations, which covers the per-item-group cap of 150 products with
 * the 3x headroom the spec requires. The self-check refuses to write a workbook whose
 * pools are too small.
 * ขนาดของคลังคำเป็นข้อบังคับ ไม่ใช่เรื่องรูปแบบ
 */

/** @typedef {{ en: string, th: string }} Term */

/** Shared across every item group. / ใช้ร่วมกันทุกกลุ่มสินค้า */
export const SIZES = [
  { en: '100 g', th: '100 ก.' },
  { en: '250 g', th: '250 ก.' },
  { en: '500 g', th: '500 ก.' },
  { en: '1 kg', th: '1 กก.' },
  { en: '5 kg', th: '5 กก.' },
  { en: '330 ml', th: '330 มล.' },
  { en: '750 ml', th: '750 มล.' },
  { en: '1 L', th: '1 ล.' },
];

/** Keyed by CATEGORY code. / จัดกลุ่มตามรหัสหมวด */
export const VARIANTS = {
  '1': [
    { en: 'Grade A', th: 'เกรด เอ' },
    { en: 'Premium', th: 'พรีเมียม' },
    { en: 'Imported', th: 'นำเข้า' },
    { en: 'Local', th: 'ในประเทศ' },
    { en: 'Organic', th: 'ออร์แกนิก' },
    { en: 'Frozen', th: 'แช่แข็ง' },
    { en: 'Chilled', th: 'แช่เย็น' },
    { en: 'Dried', th: 'อบแห้ง' },
  ],
  '2': [
    { en: 'Reserve', th: 'รีเซิร์ฟ' },
    { en: 'Aged 12Y', th: 'บ่ม 12 ปี' },
    { en: 'Single Barrel', th: 'ซิงเกิลบาร์เรล' },
    { en: 'Blended', th: 'เบลนด์' },
    { en: 'Dry', th: 'ดราย' },
    { en: 'Extra Dry', th: 'เอ็กซ์ตราดราย' },
    { en: 'Light', th: 'ไลต์' },
    { en: 'Classic', th: 'คลาสสิก' },
  ],
  // '3' SUPPLIES — axes: grade / scent / pack size.
  '3': [
    { en: 'Economy Grade', th: 'เกรดประหยัด' },
    { en: 'Standard Pack', th: 'แพ็กมาตรฐาน' },
    { en: 'Lavender Scent', th: 'กลิ่นลาเวนเดอร์' },
    { en: 'Citrus Scent', th: 'กลิ่นซิตรัส' },
    { en: 'Unscented', th: 'ไม่มีกลิ่น' },
    { en: 'Bulk Pack', th: 'แพ็กใหญ่' },
    { en: 'Travel Size', th: 'ขนาดพกพา' },
    { en: 'Refill Pack', th: 'แพ็กเติม' },
  ],
  // '4' ENGINEERING SUPPLIES — axes: rating / material / finish.
  '4': [
    { en: 'Heavy Duty', th: 'สำหรับงานหนัก' },
    { en: 'Stainless Steel', th: 'สแตนเลส' },
    { en: 'Galvanized', th: 'ชุบกัลวาไนซ์' },
    { en: 'Matte Finish', th: 'ผิวด้าน' },
    { en: 'Glossy Finish', th: 'ผิวมัน' },
    { en: 'Industrial Grade', th: 'เกรดอุตสาหกรรม' },
    { en: 'Waterproof Rated', th: 'กันน้ำ' },
    { en: 'Corrosion Resistant', th: 'ทนการกัดกร่อน' },
  ],
  // '5' OTHERS — one item group, neutral generic variants.
  '5': [
    { en: 'General Purpose', th: 'อเนกประสงค์' },
    { en: 'Standard', th: 'มาตรฐาน' },
    { en: 'Assorted', th: 'คละแบบ' },
    { en: 'Basic', th: 'พื้นฐาน' },
    { en: 'Value Pack', th: 'แพ็กคุ้มค่า' },
    { en: 'Special', th: 'พิเศษ' },
    { en: 'Seasonal', th: 'ตามฤดูกาล' },
    { en: 'Limited', th: 'จำนวนจำกัด' },
  ],
  // '6' SOE — axes: material / pattern / finish.
  '6': [
    { en: 'Heavyweight', th: 'เนื้อหนา' },
    { en: 'Porcelain', th: 'พอร์ซเลน' },
    { en: 'Hotel Standard', th: 'มาตรฐานโรงแรม' },
    { en: 'Solid Colour', th: 'สีพื้น' },
    { en: 'Printed Pattern', th: 'ลายพิมพ์' },
    { en: 'Polished Finish', th: 'ผิวขัดเงา' },
    { en: 'Brushed Finish', th: 'ผิวขัดด้าน' },
    { en: 'Embossed Pattern', th: 'ลายนูน' },
  ],
};

/** Keyed by ITEM GROUP code. One key per entry of catalog.ITEM_GROUPS. */
export const BASES = {
  // ---- Category 1 FOOD -----------------------------------------------------------
  '1000': [ // SAUCE & SEASONING
    { en: 'Oyster Sauce', th: 'ซอสหอยนางรม' },
    { en: 'Fish Sauce', th: 'น้ำปลา' },
    { en: 'Soy Sauce', th: 'ซีอิ๊วขาว' },
    { en: 'Chilli Paste', th: 'น้ำพริกเผา' },
    { en: 'Curry Paste', th: 'พริกแกง' },
    { en: 'Tomato Ketchup', th: 'ซอสมะเขือเทศ' },
    { en: 'Vinegar', th: 'น้ำส้มสายชู' },
    { en: 'Sesame Oil', th: 'น้ำมันงา' },
  ],
  '1001': [ // FOOD CAN & PICKLES
    { en: 'Canned Tuna', th: 'ปลาทูน่ากระป๋อง' },
    { en: 'Canned Corn', th: 'ข้าวโพดกระป๋อง' },
    { en: 'Canned Mushroom', th: 'เห็ดกระป๋อง' },
    { en: 'Pickled Cucumber', th: 'แตงกวาดอง' },
    { en: 'Pickled Ginger', th: 'ขิงดอง' },
    { en: 'Canned Peas', th: 'ถั่วลันเตากระป๋อง' },
    { en: 'Canned Pineapple', th: 'สับปะรดกระป๋อง' },
    { en: 'Pickled Garlic', th: 'กระเทียมดอง' },
  ],
  '1002': [ // SUGAR & SWEETENER
    { en: 'White Sugar', th: 'น้ำตาลทราย' },
    { en: 'Brown Sugar', th: 'น้ำตาลทรายแดง' },
    { en: 'Palm Sugar', th: 'น้ำตาลปี๊บ' },
    { en: 'Rock Sugar', th: 'น้ำตาลกรวด' },
    { en: 'Honey', th: 'น้ำผึ้ง' },
    { en: 'Artificial Sweetener', th: 'สารให้ความหวานแทนน้ำตาล' },
    { en: 'Icing Sugar', th: 'น้ำตาลไอซิ่ง' },
    { en: 'Syrup', th: 'น้ำเชื่อม' },
  ],
  '1003': [ // MILK & CREAM
    { en: 'Fresh Milk', th: 'นมสด' },
    { en: 'Whipping Cream', th: 'วิปปิ้งครีม' },
    { en: 'Condensed Milk', th: 'นมข้นหวาน' },
    { en: 'Evaporated Milk', th: 'นมข้นจืด' },
    { en: 'Coconut Milk', th: 'กะทิ' },
    { en: 'Sour Cream', th: 'ครีมเปรี้ยว' },
    { en: 'Non-Dairy Creamer', th: 'ครีมเทียม' },
    { en: 'Yoghurt Drink', th: 'นมเปรี้ยว' },
  ],
  '1004': [ // FOOD JUICE
    { en: 'Orange Juice', th: 'น้ำส้ม' },
    { en: 'Apple Juice', th: 'น้ำแอปเปิ้ล' },
    { en: 'Mixed Fruit Juice', th: 'น้ำผลไม้รวม' },
    { en: 'Tomato Juice', th: 'น้ำมะเขือเทศ' },
    { en: 'Pineapple Juice', th: 'น้ำสับปะรด' },
    { en: 'Guava Juice', th: 'น้ำฝรั่ง' },
    { en: 'Lychee Juice', th: 'น้ำลิ้นจี่' },
    { en: 'Lime Juice Concentrate', th: 'น้ำมะนาวเข้มข้น' },
  ],
  '1005': [ // COFFEE & TEA
    { en: 'Arabica Coffee Bean', th: 'เมล็ดกาแฟอาราบิก้า' },
    { en: 'Instant Coffee', th: 'กาแฟสำเร็จรูป' },
    { en: 'Thai Tea', th: 'ชาไทย' },
    { en: 'Green Tea', th: 'ชาเขียว' },
    { en: 'Black Tea Bag', th: 'ชาดำแบบซอง' },
    { en: 'Espresso Ground Coffee', th: 'กาแฟบดสำหรับเอสเพรสโซ' },
    { en: 'Jasmine Tea', th: 'ชามะลิ' },
    { en: 'Chrysanthemum Tea', th: 'ชาเก๊กฮวย' },
  ],
  '1006': [ // JAM & BAKERY
    { en: 'Strawberry Jam', th: 'แยมสตรอว์เบอร์รี' },
    { en: 'Orange Marmalade', th: 'แยมส้ม' },
    { en: 'Butter Croissant', th: 'ครัวซองต์เนย' },
    { en: 'White Bread Loaf', th: 'ขนมปังแถว' },
    { en: 'Puff Pastry', th: 'แป้งพัฟ' },
    { en: 'Chocolate Spread', th: 'ช็อกโกแลตทาขนมปัง' },
    { en: 'Peanut Butter', th: 'เนยถั่ว' },
    { en: 'Danish Pastry', th: 'ขนมปังเดนิช' },
  ],
  '1007': [ // NOODLE & FLOUR
    { en: 'Rice Vermicelli', th: 'เส้นหมี่' },
    { en: 'Egg Noodle', th: 'บะหมี่ไข่' },
    { en: 'Glass Noodle', th: 'วุ้นเส้น' },
    { en: 'All-Purpose Flour', th: 'แป้งอเนกประสงค์' },
    { en: 'Rice Flour', th: 'แป้งข้าวเจ้า' },
    { en: 'Tapioca Starch', th: 'แป้งมันสำปะหลัง' },
    { en: 'Bread Flour', th: 'แป้งขนมปัง' },
    { en: 'Instant Noodle', th: 'บะหมี่กึ่งสำเร็จรูป' },
  ],
  '1008': [ // HERBS & SPICES
    { en: 'Black Pepper', th: 'พริกไทยดำ' },
    { en: 'Dried Chilli', th: 'พริกแห้ง' },
    { en: 'Cumin Seed', th: 'เมล็ดยี่หร่า' },
    { en: 'Coriander Seed', th: 'เมล็ดผักชี' },
    { en: 'Bay Leaf', th: 'ใบกระวาน' },
    { en: 'Cinnamon Stick', th: 'อบเชย' },
    { en: 'Star Anise', th: 'โป๊ยกั๊ก' },
    { en: 'Turmeric Powder', th: 'ผงขมิ้น' },
  ],
  '1009': [ // OIL & BUTTER
    { en: 'Vegetable Oil', th: 'น้ำมันพืช' },
    { en: 'Olive Oil', th: 'น้ำมันมะกอก' },
    { en: 'Palm Oil', th: 'น้ำมันปาล์ม' },
    { en: 'Butter', th: 'เนย' },
    { en: 'Margarine', th: 'มาการีน' },
    { en: 'Ghee', th: 'เนยใส' },
    { en: 'Corn Oil', th: 'น้ำมันข้าวโพด' },
    { en: 'Coconut Oil', th: 'น้ำมันมะพร้าว' },
  ],
  '1100': [ // SEAFOOD
    { en: 'Tiger Prawn', th: 'กุ้งลายเสือ' },
    { en: 'Sea Bass', th: 'ปลากะพง' },
    { en: 'Salmon Fillet', th: 'เนื้อปลาแซลมอน' },
    { en: 'Blue Crab', th: 'ปูม้า' },
    { en: 'Squid Tube', th: 'ปลาหมึกกล้วย' },
    { en: 'Green Mussel', th: 'หอยแมลงภู่' },
    { en: 'River Prawn', th: 'กุ้งแม่น้ำ' },
    { en: 'Red Snapper', th: 'ปลากะพงแดง' },
  ],
  '1101': [ // MEAT & POULTRY
    { en: 'Chicken Breast', th: 'อกไก่' },
    { en: 'Chicken Thigh', th: 'สะโพกไก่' },
    { en: 'Pork Loin', th: 'หมูสันนอก' },
    { en: 'Pork Belly', th: 'หมูสามชั้น' },
    { en: 'Beef Sirloin', th: 'เนื้อสันนอก' },
    { en: 'Duck Breast', th: 'อกเป็ด' },
    { en: 'Minced Pork', th: 'หมูสับ' },
    { en: 'Turkey Breast', th: 'อกไก่งวง' },
  ],
  '1102': [ // VEGETABLE
    { en: 'Chinese Kale', th: 'คะน้า' },
    { en: 'Cabbage', th: 'กะหล่ำปลี' },
    { en: 'Carrot', th: 'แครอท' },
    { en: 'Tomato', th: 'มะเขือเทศ' },
    { en: 'Cucumber', th: 'แตงกวา' },
    { en: 'Lettuce', th: 'ผักกาดหอม' },
    { en: 'Bell Pepper', th: 'พริกหวาน' },
    { en: 'Bean Sprout', th: 'ถั่วงอก' },
  ],
  '1103': [ // FRUIT
    { en: 'Banana', th: 'กล้วย' },
    { en: 'Papaya', th: 'มะละกอ' },
    { en: 'Watermelon', th: 'แตงโม' },
    { en: 'Pineapple', th: 'สับปะรด' },
    { en: 'Mango', th: 'มะม่วง' },
    { en: 'Dragon Fruit', th: 'แก้วมังกร' },
    { en: 'Orange', th: 'ส้ม' },
    { en: 'Apple', th: 'แอปเปิ้ล' },
  ],
  '1104': [ // DAIRY
    { en: 'Cheddar Cheese', th: 'ชีสเชดดาร์' },
    { en: 'Mozzarella Cheese', th: 'ชีสมอสซาเรลลา' },
    { en: 'Butter Block', th: 'เนยแท่ง' },
    { en: 'Cream Cheese', th: 'ครีมชีส' },
    { en: 'Parmesan Cheese', th: 'ชีสพาร์เมซาน' },
    { en: 'Plain Yoghurt', th: 'โยเกิร์ตรสธรรมชาติ' },
    { en: 'Whipped Butter', th: 'เนยตีฟู' },
    { en: 'Fresh Cream', th: 'ครีมสด' },
  ],
  '1105': [ // ICE CREAM
    { en: 'Vanilla Ice Cream', th: 'ไอศกรีมวานิลลา' },
    { en: 'Chocolate Ice Cream', th: 'ไอศกรีมช็อกโกแลต' },
    { en: 'Strawberry Ice Cream', th: 'ไอศกรีมสตรอว์เบอร์รี' },
    { en: 'Coconut Ice Cream', th: 'ไอศกรีมมะพร้าว' },
    { en: 'Mango Sorbet', th: 'ซอร์เบต์มะม่วง' },
    { en: 'Cookies & Cream Ice Cream', th: 'ไอศกรีมคุกกี้แอนด์ครีม' },
    { en: 'Green Tea Ice Cream', th: 'ไอศกรีมชาเขียว' },
    { en: 'Ice Cream Cone', th: 'ไอศกรีมโคน' },
  ],

  // ---- Category 2 BEVERAGE --------------------------------------------------------
  '2000': [ // SCOTCH WHISKY
    { en: 'Single Malt Scotch', th: 'สก็อตวิสกี้ซิงเกิลมอลต์' },
    { en: 'Blended Scotch', th: 'สก็อตวิสกี้เบลนด์' },
    { en: 'Highland Scotch', th: 'สก็อตวิสกี้ไฮแลนด์' },
    { en: 'Speyside Scotch', th: 'สก็อตวิสกี้สเปย์ไซด์' },
    { en: 'Islay Scotch', th: 'สก็อตวิสกี้ไอเลย์' },
    { en: 'Peated Scotch', th: 'สก็อตวิสกี้กลิ่นควันพีท' },
    { en: 'Cask Strength Scotch', th: 'สก็อตวิสกี้ความเข้มข้นระดับถัง' },
    { en: 'Vatted Malt Scotch', th: 'สก็อตวิสกี้แวตเต็ดมอลต์' },
  ],
  '2001': [ // CANADIAN
    { en: 'Canadian Blended Whisky', th: 'แคนาเดียนวิสกี้เบลนด์' },
    { en: 'Canadian Rye Whisky', th: 'แคนาเดียนไรย์วิสกี้' },
    { en: 'Canadian Corn Whisky', th: 'แคนาเดียนคอร์นวิสกี้' },
    { en: 'Canadian Light Whisky', th: 'แคนาเดียนวิสกี้ไลต์' },
    { en: 'Canadian Aged Whisky', th: 'แคนาเดียนวิสกี้บ่มนาน' },
    { en: 'Canadian Premium Whisky', th: 'แคนาเดียนวิสกี้พรีเมียม' },
    { en: 'Canadian Rye-Corn Blend', th: 'แคนาเดียนไรย์คอร์นเบลนด์' },
    { en: 'Canadian Wheat Whisky', th: 'แคนาเดียนวิสกี้ข้าวสาลี' },
  ],
  '2002': [ // BOURBON
    { en: 'Kentucky Straight Bourbon', th: 'เคนตักกีสเตรทเบอร์เบิน' },
    { en: 'Small Batch Bourbon', th: 'เบอร์เบินสมอลแบทช์' },
    { en: 'Single Barrel Bourbon', th: 'เบอร์เบินซิงเกิลบาร์เรล' },
    { en: 'Wheated Bourbon', th: 'เบอร์เบินสูตรข้าวสาลี' },
    { en: 'Cask Strength Bourbon', th: 'เบอร์เบินความเข้มข้นระดับถัง' },
    { en: 'High Rye Bourbon', th: 'เบอร์เบินไรย์สูง' },
    { en: 'Bottled-in-Bond Bourbon', th: 'เบอร์เบินบอตเทิลอินบอนด์' },
    { en: 'Sour Mash Bourbon', th: 'เบอร์เบินซาวร์แมช' },
  ],
  '2003': [ // THAI WHISKY
    { en: 'White Spirit Whisky', th: 'เหล้าขาว' },
    { en: 'Rice Whisky', th: 'สุราไทยจากข้าว' },
    { en: 'Blended Thai Whisky', th: 'วิสกี้ไทยเบลนด์' },
    { en: 'Herbal Infused Whisky', th: 'วิสกี้แช่สมุนไพร' },
    { en: 'Golden Thai Whisky', th: 'วิสกี้ไทยสีทอง' },
    { en: 'Premium Thai Whisky', th: 'วิสกี้ไทยพรีเมียม' },
    { en: 'Aged Thai Whisky', th: 'วิสกี้ไทยบ่มนาน' },
    { en: 'Spiced Thai Whisky', th: 'วิสกี้ไทยผสมเครื่องเทศ' },
  ],
  '2004': [ // SAKE
    { en: 'Junmai Sake', th: 'สาเกจุนไม' },
    { en: 'Ginjo Sake', th: 'สาเกกินโจ' },
    { en: 'Daiginjo Sake', th: 'สาเกไดกินโจ' },
    { en: 'Nigori Sake', th: 'สาเกนิโกริ' },
    { en: 'Sparkling Sake', th: 'สาเกซ่า' },
    { en: 'Honjozo Sake', th: 'สาเกฮอนโจโซ' },
    { en: 'Cold Sake', th: 'สาเกเย็น' },
    { en: 'Warm Sake', th: 'สาเกอุ่น' },
  ],
  '2005': [ // BRANDY & COGNAC
    { en: 'VS Cognac', th: 'คอนญักวีเอส' },
    { en: 'VSOP Cognac', th: 'คอนญักวีเอสโอพี' },
    { en: 'XO Cognac', th: 'คอนญักเอ็กซ์โอ' },
    { en: 'Grape Brandy', th: 'บรั่นดีองุ่น' },
    { en: 'Fruit Brandy', th: 'บรั่นดีผลไม้' },
    { en: 'Aged Brandy', th: 'บรั่นดีบ่มนาน' },
    { en: 'Napoleon Brandy', th: 'บรั่นดีนโปเลียน' },
    { en: 'Armagnac', th: 'อาร์มาญัก' },
  ],
  '2006': [ // WINE & ROSE
    { en: 'Red Wine', th: 'ไวน์แดง' },
    { en: 'White Wine', th: 'ไวน์ขาว' },
    { en: 'Rose Wine', th: 'ไวน์โรเซ่' },
    { en: 'Sparkling Wine', th: 'ไวน์สปาร์กลิง' },
    { en: 'Dessert Wine', th: 'ไวน์หวาน' },
    { en: 'House Red Wine', th: 'ไวน์แดงเฮาส์' },
    { en: 'Dry White Wine', th: 'ไวน์ขาวดราย' },
    { en: 'Fortified Wine', th: 'ไวน์เสริมแอลกอฮอล์' },
  ],
  '2007': [ // GIN & VODKA
    { en: 'London Dry Gin', th: 'จินลอนดอนดราย' },
    { en: 'Botanical Gin', th: 'จินสมุนไพร' },
    { en: 'Plain Vodka', th: 'วอดก้าธรรมดา' },
    { en: 'Flavoured Vodka', th: 'วอดก้ามีกลิ่นรส' },
    { en: 'Navy Strength Gin', th: 'จินเนวีสเตรงท์' },
    { en: 'Potato Vodka', th: 'วอดก้ามันฝรั่ง' },
    { en: 'Sloe Gin', th: 'จินสโล' },
    { en: 'Citrus Vodka', th: 'วอดก้ากลิ่นซิตรัส' },
  ],
  '2008': [ // RUM
    { en: 'White Rum', th: 'รัมขาว' },
    { en: 'Dark Rum', th: 'รัมดำ' },
    { en: 'Spiced Rum', th: 'รัมผสมเครื่องเทศ' },
    { en: 'Golden Rum', th: 'รัมสีทอง' },
    { en: 'Aged Rum', th: 'รัมบ่มนาน' },
    { en: 'Overproof Rum', th: 'รัมโอเวอร์พรูฟ' },
    { en: 'Coconut Rum', th: 'รัมกลิ่นมะพร้าว' },
    { en: 'Navy Rum', th: 'รัมเนวี' },
  ],
  '2009': [ // LIQUEUR
    { en: 'Coffee Liqueur', th: 'ลิเคียวร์กาแฟ' },
    { en: 'Orange Liqueur', th: 'ลิเคียวร์ส้ม' },
    { en: 'Herbal Liqueur', th: 'ลิเคียวร์สมุนไพร' },
    { en: 'Almond Liqueur', th: 'ลิเคียวร์อัลมอนด์' },
    { en: 'Cream Liqueur', th: 'ลิเคียวร์ครีม' },
    { en: 'Cherry Liqueur', th: 'ลิเคียวร์เชอร์รี' },
    { en: 'Melon Liqueur', th: 'ลิเคียวร์เมลอน' },
    { en: 'Triple Sec', th: 'ทริปเปิลเซค' },
  ],
  '2010': [ // CHAMPAGNE
    { en: 'Brut Champagne', th: 'แชมเปญบรุต' },
    { en: 'Rose Champagne', th: 'แชมเปญโรเซ่' },
    { en: 'Vintage Champagne', th: 'แชมเปญวินเทจ' },
    { en: 'Demi-Sec Champagne', th: 'แชมเปญเดมิเซค' },
    { en: 'Blanc de Blancs', th: 'บลองก์เดอบลองก์' },
    { en: 'Extra Brut Champagne', th: 'แชมเปญเอ็กซ์ตราบรุต' },
    { en: 'Prestige Cuvee', th: 'พรีสตีจคูเว่' },
    { en: 'Non-Vintage Champagne', th: 'แชมเปญนอนวินเทจ' },
  ],
  '2011': [ // APERITIF
    { en: 'Dry Vermouth', th: 'เวอร์มุตดราย' },
    { en: 'Sweet Vermouth', th: 'เวอร์มุตหวาน' },
    { en: 'Aromatic Bitters', th: 'บิทเทอร์กลิ่นหอม' },
    { en: 'Herbal Aperitif', th: 'อะเปอริทีฟสมุนไพร' },
    { en: 'Citrus Aperitif', th: 'อะเปอริทีฟกลิ่นซิตรัส' },
    { en: 'Anise Aperitif', th: 'อะเปอริทีฟกลิ่นโป๊ยกั๊ก' },
    { en: 'Fortified Aperitif Wine', th: 'ไวน์อะเปอริทีฟเสริมแอลกอฮอล์' },
    { en: 'Quinine Aperitif', th: 'อะเปอริทีฟควินิน' },
  ],
  '2012': [ // BEER
    { en: 'Lager Beer', th: 'เบียร์ลาเกอร์' },
    { en: 'Wheat Beer', th: 'เบียร์ข้าวสาลี' },
    { en: 'Pale Ale', th: 'เพลเอล' },
    { en: 'Stout', th: 'สเตาต์' },
    { en: 'Pilsner', th: 'พิลส์เนอร์' },
    { en: 'Draught Beer', th: 'เบียร์สด' },
    { en: 'Craft Beer', th: 'คราฟต์เบียร์' },
    { en: 'Non-Alcoholic Beer', th: 'เบียร์ไร้แอลกอฮอล์' },
  ],
  '2013': [ // SOFT DRINK
    { en: 'Cola', th: 'น้ำอัดลมโคล่า' },
    { en: 'Lemon-Lime Soda', th: 'น้ำอัดลมมะนาว' },
    { en: 'Orange Soda', th: 'น้ำอัดลมส้ม' },
    { en: 'Soda Water', th: 'โซดา' },
    { en: 'Tonic Water', th: 'โทนิกวอเตอร์' },
    { en: 'Ginger Ale', th: 'น้ำขิงอัดลม' },
    { en: 'Root Beer', th: 'รูทเบียร์' },
    { en: 'Energy Drink', th: 'เครื่องดื่มชูกำลัง' },
  ],

  // ---- Category 3 SUPPLIES ---------------------------------------------------------
  '3000': [ // CLEANING SUPPLIES
    { en: 'Glass Cleaner', th: 'น้ำยาเช็ดกระจก' },
    { en: 'All-Purpose Cleaner', th: 'น้ำยาทำความสะอาดอเนกประสงค์' },
    { en: 'Floor Cleaner', th: 'น้ำยาถูพื้น' },
    { en: 'Toilet Bowl Cleaner', th: 'น้ำยาล้างห้องน้ำ' },
    { en: 'Disinfectant Spray', th: 'สเปรย์ฆ่าเชื้อ' },
    { en: 'Furniture Polish', th: 'น้ำยาขัดเงาเฟอร์นิเจอร์' },
    { en: 'Degreaser', th: 'น้ำยาขจัดคราบมัน' },
    { en: 'Bleach', th: 'น้ำยาฟอกขาว' },
  ],
  '3100': [ // GENERAL SUPPLIES
    { en: 'Trash Bag', th: 'ถุงขยะ' },
    { en: 'Rubber Glove', th: 'ถุงมือยาง' },
    { en: 'Cleaning Cloth', th: 'ผ้าเช็ดทำความสะอาด' },
    { en: 'Air Freshener', th: 'สเปรย์ปรับอากาศ' },
    { en: 'Sponge', th: 'ฟองน้ำ' },
    { en: 'Broom', th: 'ไม้กวาด' },
    { en: 'Mop Head', th: 'หัวไม้ถูพื้น' },
    { en: 'Dust Pan', th: 'ที่โกยผง' },
  ],
  '3200': [ // GUEST SUPPLIES
    { en: 'Shampoo Bottle', th: 'แชมพูขวด' },
    { en: 'Body Lotion', th: 'โลชั่นบำรุงผิว' },
    { en: 'Bath Soap', th: 'สบู่ก้อน' },
    { en: 'Toothbrush Set', th: 'ชุดแปรงสีฟัน' },
    { en: 'Shower Cap', th: 'หมวกอาบน้ำ' },
    { en: 'Cotton Bud', th: 'สำลีก้าน' },
    { en: 'Slipper', th: 'รองเท้าแตะ' },
    { en: 'Sewing Kit', th: 'ชุดเข็มด้าย' },
  ],
  '3300': [ // LAUNDRY SUPPLIES
    { en: 'Laundry Detergent', th: 'ผงซักฟอก' },
    { en: 'Fabric Softener', th: 'น้ำยาปรับผ้านุ่ม' },
    { en: 'Stain Remover', th: 'น้ำยาขจัดคราบ' },
    { en: 'Laundry Bag', th: 'ถุงผ้าซักรีด' },
    { en: 'Starch Spray', th: 'สเปรย์แป้งรีดผ้า' },
    { en: 'Bleaching Powder', th: 'ผงฟอกขาว' },
    { en: 'Dry Cleaning Bag', th: 'ถุงซักแห้ง' },
    { en: 'Ironing Sheet', th: 'ผ้ารองรีด' },
  ],
  '3400': [ // PRINTING & STATIONERY
    { en: 'A4 Paper', th: 'กระดาษ A4' },
    { en: 'Ballpoint Pen', th: 'ปากกาลูกลื่น' },
    { en: 'Printer Toner', th: 'ตลับหมึกเครื่องพิมพ์' },
    { en: 'Envelope', th: 'ซองจดหมาย' },
    { en: 'Sticky Note', th: 'กระดาษโน้ตกาว' },
    { en: 'Stapler', th: 'เครื่องเย็บกระดาษ' },
    { en: 'Name Card', th: 'นามบัตร' },
    { en: 'Guest Comment Card', th: 'บัตรความคิดเห็นแขก' },
  ],
  '3500': [ // FLOWER STORE
    { en: 'Fresh Rose', th: 'กุหลาบสด' },
    { en: 'Orchid Bunch', th: 'กล้วยไม้ช่อ' },
    { en: 'Floral Foam', th: 'โฟมปักดอกไม้' },
    { en: 'Vase', th: 'แจกัน' },
    { en: 'Greenery Filler', th: 'ใบไม้ประดับช่อ' },
    { en: 'Table Centerpiece', th: 'ดอกไม้กลางโต๊ะ' },
    { en: 'Lily Bunch', th: 'ลิลลี่ช่อ' },
    { en: 'Ribbon Roll', th: 'ริบบิ้นม้วน' },
  ],
  '3600': [ // SPA SUPPLIES
    { en: 'Massage Oil', th: 'น้ำมันนวด' },
    { en: 'Aromatherapy Candle', th: 'เทียนหอมอะโรมา' },
    { en: 'Herbal Compress Ball', th: 'ลูกประคบสมุนไพร' },
    { en: 'Body Scrub', th: 'ครีมขัดผิว' },
    { en: 'Essential Oil', th: 'น้ำมันหอมระเหย' },
    { en: 'Spa Towel', th: 'ผ้าขนหนูสปา' },
    { en: 'Facial Mask', th: 'มาส์กหน้า' },
    { en: 'Bath Salt', th: 'เกลืออาบน้ำ' },
  ],
  '3700': [ // GAS
    { en: 'LPG Cylinder', th: 'ถังแก๊สแอลพีจี' },
    { en: 'Cooking Gas Refill', th: 'แก๊สหุงต้มเติม' },
    { en: 'Propane Tank', th: 'ถังแก๊สโพรเพน' },
    { en: 'Butane Canister', th: 'กระป๋องแก๊สบิวเทน' },
    { en: 'Gas Regulator', th: 'หัวปรับแก๊ส' },
    { en: 'Gas Hose', th: 'สายแก๊ส' },
    { en: 'Portable Gas Burner', th: 'เตาแก๊สพกพา' },
    { en: 'Industrial Gas Cylinder', th: 'ถังแก๊สอุตสาหกรรม' },
  ],
  '3800': [ // OTHERS SUPPLIES
    { en: 'Packing Tape', th: 'เทปกาวพัสดุ' },
    { en: 'Cable Tie', th: 'เคเบิ้ลไทร์' },
    { en: 'Safety Pin', th: 'เข็มกลัดซ่อนปลาย' },
    { en: 'Rubber Band', th: 'หนังยาง' },
    { en: 'String Roll', th: 'เชือกม้วน' },
    { en: 'Storage Box', th: 'กล่องเก็บของ' },
    { en: 'Plastic Wrap', th: 'พลาสติกห่ออาหาร' },
    { en: 'Aluminium Foil', th: 'ฟอยล์อะลูมิเนียม' },
  ],
  '3900': [ // TOBACCO
    { en: 'Filtered Cigarette', th: 'บุหรี่ก้นกรอง' },
    { en: 'Cigar', th: 'ซิการ์' },
    { en: 'Rolling Tobacco', th: 'ยาเส้นมวนเอง' },
    { en: 'Rolling Paper', th: 'กระดาษมวนบุหรี่' },
    { en: 'Menthol Cigarette', th: 'บุหรี่เมนทอล' },
    { en: 'Cigarette Lighter', th: 'ไฟแช็ก' },
    { en: 'Ashtray', th: 'ที่เขี่ยบุหรี่' },
    { en: 'Tobacco Pouch', th: 'ถุงใส่ยาเส้น' },
  ],

  // ---- Category 4 ENGINEERING SUPPLIES ---------------------------------------------
  '4000': [ // NEON / BULBS
    { en: 'LED Bulb', th: 'หลอดไฟแอลอีดี' },
    { en: 'Fluorescent Tube', th: 'หลอดฟลูออเรสเซนต์' },
    { en: 'Neon Sign Tube', th: 'หลอดนีออน' },
    { en: 'Halogen Bulb', th: 'หลอดฮาโลเจน' },
    { en: 'Spotlight Bulb', th: 'หลอดสปอตไลต์' },
    { en: 'Emergency Light Bulb', th: 'หลอดไฟฉุกเฉิน' },
    { en: 'Decorative String Light', th: 'ไฟประดับสาย' },
    { en: 'Ballast', th: 'บัลลาสต์' },
  ],
  '4100': [ // ELECTRICAL
    { en: 'Electrical Wire', th: 'สายไฟฟ้า' },
    { en: 'Circuit Breaker', th: 'เบรกเกอร์' },
    { en: 'Power Socket', th: 'เต้ารับไฟฟ้า' },
    { en: 'Extension Cord', th: 'สายพ่วงไฟ' },
    { en: 'Electrical Tape', th: 'เทปพันสายไฟ' },
    { en: 'Junction Box', th: 'กล่องต่อสายไฟ' },
    { en: 'Fuse', th: 'ฟิวส์' },
    { en: 'Switch Plate', th: 'แผงสวิตช์ไฟ' },
  ],
  '4200': [ // BUILDING
    { en: 'Cement Bag', th: 'ปูนซีเมนต์ถุง' },
    { en: 'Ceramic Tile', th: 'กระเบื้องเซรามิก' },
    { en: 'Plywood Sheet', th: 'แผ่นไม้อัด' },
    { en: 'Steel Rebar', th: 'เหล็กเส้น' },
    { en: 'Sand', th: 'ทราย' },
    { en: 'Gypsum Board', th: 'แผ่นยิปซัม' },
    { en: 'Concrete Block', th: 'บล็อกคอนกรีต' },
    { en: 'Roof Sheet', th: 'แผ่นหลังคา' },
  ],
  '4300': [ // PLUMBING & HEATING
    { en: 'PVC Pipe', th: 'ท่อพีวีซี' },
    { en: 'Copper Pipe', th: 'ท่อทองแดง' },
    { en: 'Gate Valve', th: 'วาล์วประตูน้ำ' },
    { en: 'Water Heater', th: 'เครื่องทำน้ำอุ่น' },
    { en: 'Faucet', th: 'ก๊อกน้ำ' },
    { en: 'Pipe Fitting', th: 'ข้อต่อท่อ' },
    { en: 'Check Valve', th: 'เช็ควาล์ว' },
    { en: 'Water Pump', th: 'ปั๊มน้ำ' },
  ],
  '4400': [ // FURNITURE
    { en: 'Office Chair', th: 'เก้าอี้สำนักงาน' },
    { en: 'Wooden Table', th: 'โต๊ะไม้' },
    { en: 'Bookshelf', th: 'ชั้นวางหนังสือ' },
    { en: 'Sofa Set', th: 'ชุดโซฟา' },
    { en: 'Filing Cabinet', th: 'ตู้เก็บเอกสาร' },
    { en: 'Bed Frame', th: 'โครงเตียง' },
    { en: 'Dining Chair', th: 'เก้าอี้รับประทานอาหาร' },
    { en: 'Wardrobe', th: 'ตู้เสื้อผ้า' },
  ],
  '4500': [ // OTHER REPAIR & MAINTENANCE
    { en: 'Adhesive Sealant', th: 'กาวซีลแลนต์' },
    { en: 'Lubricant Spray', th: 'สเปรย์หล่อลื่น' },
    { en: 'Sandpaper', th: 'กระดาษทราย' },
    { en: 'Touch-Up Paint', th: 'สีแต้มซ่อม' },
    { en: 'Wood Glue', th: 'กาวไม้' },
    { en: 'Rust Remover', th: 'น้ำยาขจัดสนิม' },
    { en: 'Repair Tape', th: 'เทปซ่อมแซม' },
    { en: 'Silicone Sealant', th: 'ซิลิโคนยาแนว' },
  ],
  '4600': [ // TELEPHONE MAINTENANCE
    { en: 'Telephone Handset', th: 'หูโทรศัพท์' },
    { en: 'Telephone Cable', th: 'สายโทรศัพท์' },
    { en: 'PABX Card', th: 'การ์ดตู้สาขาโทรศัพท์' },
    { en: 'Headset', th: 'หูฟังพร้อมไมค์' },
    { en: 'Telephone Line Tester', th: 'เครื่องทดสอบสายโทรศัพท์' },
    { en: 'Telephone Connector', th: 'หัวต่อสายโทรศัพท์' },
    { en: 'Cordless Phone', th: 'โทรศัพท์ไร้สาย' },
    { en: 'Telephone Battery', th: 'แบตเตอรี่โทรศัพท์' },
  ],
  '4700': [ // AIR CONDITION & REFRIGERATION
    { en: 'Air Filter', th: 'แผ่นกรองอากาศ' },
    { en: 'Refrigerant Gas', th: 'น้ำยาแอร์' },
    { en: 'Compressor', th: 'คอมเพรสเซอร์' },
    { en: 'Cooling Fan', th: 'พัดลมระบายความร้อน' },
    { en: 'Thermostat', th: 'เทอร์โมสตัท' },
    { en: 'Condenser Coil', th: 'คอยล์คอนเดนเซอร์' },
    { en: 'AC Remote Control', th: 'รีโมทแอร์' },
    { en: 'Drain Pipe', th: 'ท่อน้ำทิ้งแอร์' },
  ],
  '4800': [ // COLOUR
    { en: 'Wall Paint', th: 'สีทาผนัง' },
    { en: 'Wood Paint', th: 'สีทาไม้' },
    { en: 'Spray Paint', th: 'สีสเปรย์' },
    { en: 'Primer Paint', th: 'สีรองพื้น' },
    { en: 'Enamel Paint', th: 'สีน้ำมันเคลือบเงา' },
    { en: 'Paint Thinner', th: 'ทินเนอร์' },
    { en: 'Paint Roller', th: 'ลูกกลิ้งทาสี' },
    { en: 'Paint Brush', th: 'แปรงทาสี' },
  ],
  '4900': [ // LAUNDRY MAINTENANCE
    { en: 'Washing Machine Belt', th: 'สายพานเครื่องซักผ้า' },
    { en: 'Dryer Heating Element', th: 'ขดลวดความร้อนเครื่องอบผ้า' },
    { en: 'Laundry Machine Filter', th: 'แผ่นกรองเครื่องซักผ้า' },
    { en: 'Press Machine Pad', th: 'แผ่นรองเครื่องรีด' },
    { en: 'Steam Boiler Valve', th: 'วาล์วหม้อไอน้ำ' },
    { en: 'Ironing Machine Roller', th: 'ลูกกลิ้งเครื่องรีดผ้า' },
    { en: 'Machine Lubricant', th: 'น้ำมันหล่อลื่นเครื่องจักร' },
    { en: 'Drive Motor', th: 'มอเตอร์ขับเครื่อง' },
  ],
  '5000': [ // ENGINEERING TOOL
    { en: 'Adjustable Wrench', th: 'ประแจเลื่อน' },
    { en: 'Screwdriver Set', th: 'ชุดไขควง' },
    { en: 'Hammer', th: 'ค้อน' },
    { en: 'Measuring Tape', th: 'ตลับเมตร' },
    { en: 'Pliers', th: 'คีม' },
    { en: 'Power Drill', th: 'สว่านไฟฟ้า' },
    { en: 'Hex Key Set', th: 'ชุดประแจหกเหลี่ยม' },
    { en: 'Utility Knife', th: 'มีดคัตเตอร์' },
  ],
  '5100': [ // GARDENER & LANDSCAPING
    { en: 'Garden Hose', th: 'สายยางรดน้ำ' },
    { en: 'Lawn Mower Blade', th: 'ใบมีดตัดหญ้า' },
    { en: 'Fertilizer', th: 'ปุ๋ย' },
    { en: 'Pruning Shears', th: 'กรรไกรตัดกิ่ง' },
    { en: 'Potting Soil', th: 'ดินปลูกต้นไม้' },
    { en: 'Plant Pot', th: 'กระถางต้นไม้' },
    { en: 'Garden Rake', th: 'คราดสวน' },
    { en: 'Sprinkler Head', th: 'หัวสปริงเกลอร์' },
  ],
  '5200': [ // IT & SOFTWARE
    { en: 'USB Flash Drive', th: 'แฟลชไดรฟ์' },
    { en: 'Network Cable', th: 'สายแลน' },
    { en: 'Wireless Router', th: 'เราเตอร์ไร้สาย' },
    { en: 'Computer Mouse', th: 'เมาส์คอมพิวเตอร์' },
    { en: 'Keyboard', th: 'คีย์บอร์ด' },
    { en: 'External Hard Drive', th: 'ฮาร์ดดิสก์พกพา' },
    { en: 'Software License', th: 'ใบอนุญาตใช้ซอฟต์แวร์' },
    { en: 'Surge Protector', th: 'ปลั๊กกันไฟกระชาก' },
  ],
  '5300': [ // MACHINERY & EQUIPMENT
    { en: 'Generator Set', th: 'เครื่องปั่นไฟ' },
    { en: 'Air Compressor', th: 'เครื่องอัดอากาศ' },
    { en: 'Forklift Battery', th: 'แบตเตอรี่รถโฟล์คลิฟท์' },
    { en: 'Conveyor Belt', th: 'สายพานลำเลียง' },
    { en: 'Hydraulic Jack', th: 'แม่แรงไฮดรอลิก' },
    { en: 'Industrial Fan', th: 'พัดลมอุตสาหกรรม' },
    { en: 'Water Pump Motor', th: 'มอเตอร์ปั๊มน้ำ' },
    { en: 'Pressure Washer', th: 'เครื่องฉีดน้ำแรงดันสูง' },
  ],

  // ---- Category 5 OTHERS ------------------------------------------------------------
  '5500': [ // OTHERS
    { en: 'Miscellaneous Item', th: 'สินค้าเบ็ดเตล็ด' },
    { en: 'General Consumable', th: 'วัสดุสิ้นเปลืองทั่วไป' },
    { en: 'Spare Part', th: 'อะไหล่' },
    { en: 'Sample Item', th: 'สินค้าตัวอย่าง' },
    { en: 'Promotional Item', th: 'ของแจกส่งเสริมการขาย' },
    { en: 'Seasonal Item', th: 'สินค้าตามฤดูกาล' },
    { en: 'Unclassified Item', th: 'สินค้าไม่ระบุหมวดหมู่' },
    { en: 'Emergency Supply', th: 'เสบียงฉุกเฉิน' },
  ],

  // ---- Category 6 SOE ---------------------------------------------------------------
  '6000': [ // CHINA WARE
    { en: 'Dinner Plate', th: 'จานอาหารหลัก' },
    { en: 'Soup Bowl', th: 'ชามซุป' },
    { en: 'Tea Cup', th: 'ถ้วยชา' },
    { en: 'Side Plate', th: 'จานเล็ก' },
    { en: 'Rice Bowl', th: 'ชามข้าว' },
    { en: 'Serving Platter', th: 'จานเสิร์ฟ' },
    { en: 'Saucer', th: 'จานรองถ้วย' },
    { en: 'Coffee Cup', th: 'ถ้วยกาแฟ' },
  ],
  '6100': [ // GLASS WARE
    { en: 'Wine Glass', th: 'แก้วไวน์' },
    { en: 'Highball Glass', th: 'แก้วไฮบอล' },
    { en: 'Whisky Glass', th: 'แก้ววิสกี้' },
    { en: 'Champagne Flute', th: 'แก้วแชมเปญ' },
    { en: 'Water Goblet', th: 'แก้วน้ำก้าน' },
    { en: 'Beer Mug', th: 'แก้วเบียร์' },
    { en: 'Shot Glass', th: 'แก้วช็อต' },
    { en: 'Cocktail Glass', th: 'แก้วค็อกเทล' },
  ],
  '6200': [ // STAINLESS & SILVER WARE
    { en: 'Dinner Fork', th: 'ส้อมอาหารหลัก' },
    { en: 'Table Knife', th: 'มีดโต๊ะอาหาร' },
    { en: 'Soup Spoon', th: 'ช้อนซุป' },
    { en: 'Dessert Spoon', th: 'ช้อนของหวาน' },
    { en: 'Serving Tongs', th: 'ที่คีบเสิร์ฟ' },
    { en: 'Butter Knife', th: 'มีดทาเนย' },
    { en: 'Tea Spoon', th: 'ช้อนชา' },
    { en: 'Serving Ladle', th: 'ทัพพีเสิร์ฟ' },
  ],
  '6300': [ // BAR EQUIPMENT & TRAY
    { en: 'Cocktail Shaker', th: 'เชคเกอร์ค็อกเทล' },
    { en: 'Bar Strainer', th: 'ที่กรองบาร์' },
    { en: 'Ice Bucket', th: 'ถังใส่น้ำแข็ง' },
    { en: 'Serving Tray', th: 'ถาดเสิร์ฟ' },
    { en: 'Bottle Opener', th: 'ที่เปิดขวด' },
    { en: 'Jigger Measure', th: 'ถ้วยตวงเหล้า' },
    { en: 'Muddler', th: 'ไม้ตำค็อกเทล' },
    { en: 'Wine Decanter', th: 'ขวดเดคานเตอร์' },
  ],
  '6400': [ // KITCHEN UTENSIL
    { en: 'Chef Knife', th: 'มีดเชฟ' },
    { en: 'Cutting Board', th: 'เขียง' },
    { en: 'Frying Pan', th: 'กระทะ' },
    { en: 'Stock Pot', th: 'หม้อต้ม' },
    { en: 'Ladle', th: 'ทัพพี' },
    { en: 'Whisk', th: 'ตะกร้อตีไข่' },
    { en: 'Colander', th: 'กระชอนกรอง' },
    { en: 'Tongs', th: 'ที่คีบอาหาร' },
  ],
  '6500': [ // LINEN (ROOM, FB, SPORT)
    { en: 'Bed Sheet', th: 'ผ้าปูที่นอน' },
    { en: 'Pillow Case', th: 'ปลอกหมอน' },
    { en: 'Bath Towel', th: 'ผ้าขนหนู' },
    { en: 'Table Cloth', th: 'ผ้าปูโต๊ะ' },
    { en: 'Napkin', th: 'ผ้าเช็ดปาก' },
    { en: 'Duvet Cover', th: 'ปลอกผ้านวม' },
    { en: 'Pool Towel', th: 'ผ้าเช็ดตัวสระว่ายน้ำ' },
    { en: 'Bath Mat', th: 'พรมเช็ดเท้า' },
  ],
  '6600': [ // STAFF UNIFORM
    { en: 'Chef Jacket', th: 'เสื้อกุ๊ก' },
    { en: 'Housekeeping Apron', th: 'ผ้ากันเปื้อนแม่บ้าน' },
    { en: 'Waiter Vest', th: 'เสื้อกั๊กพนักงานเสิร์ฟ' },
    { en: 'Security Uniform Shirt', th: 'เสื้อยูนิฟอร์มรักษาความปลอดภัย' },
    { en: 'Front Office Blazer', th: 'เสื้อสูทพนักงานต้อนรับ' },
    { en: 'Kitchen Cap', th: 'หมวกครัว' },
    { en: 'Name Badge', th: 'ป้ายชื่อพนักงาน' },
    { en: 'Staff Necktie', th: 'เนคไทพนักงาน' },
  ],
  '6700': [ // HOUSEKEEPING UTENSILS
    { en: 'Cleaning Trolley', th: 'รถเข็นแม่บ้าน' },
    { en: 'Bed Making Tool', th: 'อุปกรณ์ปูเตียง' },
    { en: 'Vacuum Cleaner', th: 'เครื่องดูดฝุ่น' },
    { en: 'Dust Mop', th: 'ไม้ถูฝุ่น' },
    { en: 'Window Squeegee', th: 'ยางปาดกระจก' },
    { en: 'Spray Bottle', th: 'ขวดสเปรย์' },
    { en: 'Amenity Basket', th: 'ตะกร้าใส่ของใช้แขก' },
    { en: 'Laundry Cart', th: 'รถเข็นผ้า' },
  ],
  '6800': [ // OTHERS O.E.
    { en: 'Room Key Card', th: 'บัตรกุญแจห้องพัก' },
    { en: 'Do Not Disturb Sign', th: 'ป้ายห้ามรบกวน' },
    { en: 'Luggage Tag', th: 'ป้ายติดกระเป๋าเดินทาง' },
    { en: 'Guest Directory', th: 'คู่มือแขกในห้องพัก' },
    { en: 'Umbrella Stand', th: 'ที่วางร่ม' },
    { en: 'Welcome Card', th: 'บัตรต้อนรับ' },
    { en: 'Mini Bar Item', th: 'สินค้ามินิบาร์' },
    { en: 'Guest Slipper Bag', th: 'ถุงใส่รองเท้าแตะแขก' },
  ],
};

/**
 * Unit codes that suit each item group, most-likely first. The product generator draws the
 * inventory unit from here so a bottle of whisky is not measured in kilograms.
 * รหัสหน่วยที่เหมาะกับแต่ละกลุ่มสินค้า เรียงตามความน่าจะเป็น
 * Every value must exist in reference.UNIT_CODES.
 */
export const UNIT_HINTS = {
  // Category 1 FOOD
  '1000': ['BTL', 'CAN', 'PACK'],
  '1001': ['CAN', 'TIN', 'PACK'],
  '1002': ['KG', 'PACK', 'BAG'],
  '1003': ['CAN', 'BTL', 'PACK'],
  '1004': ['BTL', 'CAN', 'CARTON'],
  '1005': ['PACK', 'KG', 'BOX'],
  '1006': ['PACK', 'PCS', 'TIN'],
  '1007': ['KG', 'PACK', 'SACK'],
  '1008': ['KG', 'PACK', 'GRAM'],
  '1009': ['BTL', 'TIN', 'KG'],
  '1100': ['KG', 'PACK'],
  '1101': ['KG', 'PACK'],
  '1102': ['KG', 'PACK'],
  '1103': ['KG', 'PACK'],
  '1104': ['KG', 'PACK', 'PCS'],
  '1105': ['TIN', 'PACK', 'PCS'],

  // Category 2 BEVERAGE
  '2000': ['BTL', 'CASE'],
  '2001': ['BTL', 'CASE'],
  '2002': ['BTL', 'CASE'],
  '2003': ['BTL', 'CASE'],
  '2004': ['BTL', 'CASE'],
  '2005': ['BTL', 'CASE'],
  '2006': ['BTL', 'CASE'],
  '2007': ['BTL', 'CASE'],
  '2008': ['BTL', 'CASE'],
  '2009': ['BTL', 'CASE'],
  '2010': ['BTL', 'CASE'],
  '2011': ['BTL', 'CASE'],
  '2012': ['BTL', 'CAN', 'CASE'],
  '2013': ['BTL', 'CAN', 'CASE'],

  // Category 3 SUPPLIES
  '3000': ['BTL', 'GAL', 'CAN'],
  '3100': ['PACK', 'ROLL', 'PCS'],
  '3200': ['PCS', 'PACK', 'SET'],
  '3300': ['BAG', 'BTL', 'PACK'],
  '3400': ['REAM', 'BOX', 'PCS'],
  '3500': ['PCS', 'SET', 'BOX'],
  '3600': ['BTL', 'SET', 'PCS'],
  '3700': ['TANK', 'DRUM', 'UNIT'],
  '3800': ['ROLL', 'PACK', 'PCS'],
  '3900': ['PACK', 'BOX', 'CARTON'],

  // Category 4 ENGINEERING SUPPLIES
  '4000': ['PCS', 'BOX12', 'BOX24'],
  '4100': ['ROLL', 'PCS', 'METERS'],
  '4200': ['SACK', 'PCS', 'BOX'],
  '4300': ['PCS', 'METERS', 'SET'],
  '4400': ['PCS', 'SET', 'UNIT'],
  '4500': ['PCS', 'TIN', 'ROLL'],
  '4600': ['PCS', 'SET', 'UNIT'],
  '4700': ['PCS', 'TANK', 'SET'],
  '4800': ['TIN', 'DRUM', 'GAL'],
  '4900': ['PCS', 'SET', 'UNIT'],
  '5000': ['PCS', 'SET', 'UNIT'],
  '5100': ['PCS', 'BAG', 'SACK'],
  '5200': ['PCS', 'UNIT', 'SET'],
  '5300': ['UNIT', 'PCS', 'SET'],

  // Category 5 OTHERS
  '5500': ['PCS', 'UNIT', 'SET'],

  // Category 6 SOE
  '6000': ['PCS', 'SET', 'TRAY'],
  '6100': ['PCS', 'SET', 'TRAY'],
  '6200': ['PCS', 'SET', 'TRAY'],
  '6300': ['PCS', 'SET', 'TRAY'],
  '6400': ['PCS', 'SET', 'UNIT'],
  '6500': ['PCS', 'SET', 'PAIR'],
  '6600': ['PCS', 'SET', 'PAIR'],
  '6700': ['PCS', 'SET', 'UNIT'],
  '6800': ['PCS', 'SET', 'PACK'],
};
